name: dataset_collection_framework
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1j
  - pip=21.0.1
  - python=3.8.8
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - brotli==1.0.9
    - cflib==0.1.15.0
    - click==7.1.2
    - csnake==0.3.1
    - cycler==0.10.0
    - dash==1.19.0
    - dash-core-components==1.15.0
    - dash-html-components==1.1.2
    - dash-renderer==1.9.0
    - dash-table==4.11.2
    - flask==1.1.2
    - flask-compress==1.9.0
    - future==0.18.2
    - "git+https://github.com/bitcraze/crazyflie-clients-python.git@f25f72d3e8ed1e571f349ac4c2f7b9c254d4f039"
    - install==1.3.4
    - itsdangerous==1.1.0
    - jinja2==2.11.3
    - kiwisolver==1.3.1
    - markupsafe==1.1.1
    - matplotlib==3.4.1
    - numpy==1.19.2
    - opencv-python==4.5.1.48
    - pandas==1.2.3
    - pbkdf2==1.3
    - pillow==8.1.2
    - plotly==4.14.3
    - pygame==2.0.1
    - pyparsing==2.4.7
    - pyqt5==5.15.2
    - pyqt5-plugins==5.15.2.2.1.0
    - pyqt5-sip==12.8.1
    - pyqt5-tools==5.15.2.3.0.2
    - pyqtgraph==0.12.1
    - python-dateutil==2.8.1
    - python-dotenv==0.17.0
    - pytz==2021.1
    - pyusb==1.1.1
    - qled==1.3.1
    - qt5-applications==5.15.2.2.1
    - qt5-tools==5.15.2.1.0.1
    - retrying==1.3.3
    - six==1.15.0
    - werkzeug==1.0.1
